// Termos e condicoes de aceite eletronico -- versao imutavel.
// IMPORTANTE: revise com um advogado antes de virar contrato definitivo.
// Este template cobre o exigido pela Lei 14.063/2020 (assinatura eletronica
// simples), CDC art. 46 (informacao clara antes do aceite) e Codigo Civil.
// Ao trocar o conteudo, mude a versao -- todo aceite guarda a versao vigente,
// pra ser possivel provar em juizo qual texto exatamente foi aceito.
export const TERMOS_VERSAO = "1.0.0";

export function textoTermos({ nomeCliente, valorTotal, dataEvento, numConvidados, atendente }) {
  const valor = valorTotal ? `R$ ${Number(valorTotal).toLocaleString("pt-BR")}` : "o valor descrito nesta proposta";
  const evento = dataEvento ? `programado para ${new Date(`${dataEvento}T00:00:00`).toLocaleDateString("pt-BR")}` : "com data a definir";
  return [
    { titulo: "1. Objeto", corpo: `Este documento formaliza a contratação, pelo(a) CLIENTE(S) identificado(s) no aceite eletrônico, dos serviços do ESPAÇO PERSONARE EVENTOS (Ponta Grossa/PR) descritos nesta proposta — locação de espaço, pacote de serviços inclusos, buffet escolhido e extras selecionados — para evento ${evento}, com estimativa de ${numConvidados || "número a confirmar"} convidados.` },
    { titulo: "2. Preço e forma de pagamento", corpo: `O valor total contratado é ${valor}, apurado conforme o detalhamento apresentado nesta proposta. O cronograma de pagamento — incluindo sinal, parcelas intermediárias e saldo final — será formalizado em contrato específico enviado pelo ESPAÇO PERSONARE em até 5 (cinco) dias úteis contados deste aceite. Enquanto o contrato não for assinado pelas duas partes, este aceite eletrônico vale como reserva do valor e da data.` },
    { titulo: "3. Reserva e prazo dos valores", corpo: "Os valores desta proposta estão garantidos até a data de validade indicada na tela. Após essa data, e caso o contrato definitivo ainda não tenha sido assinado, o ESPAÇO PERSONARE poderá reajustar os valores conforme repasses de fornecedores (especialmente buffet), comunicando o(a) CLIENTE(S) antes de qualquer alteração." },
    { titulo: "4. Alterações e cancelamento", corpo: "Alterações no evento (data, número de convidados, buffet, extras) podem ser feitas até 30 (trinta) dias antes da data do evento, sujeitas à disponibilidade e a ajustes de valor. O cancelamento pelo(a) CLIENTE(S) implicará retenção proporcional do sinal já pago, conforme percentuais definidos no contrato definitivo. Em caso de rescisão pelo ESPAÇO PERSONARE por caso fortuito ou força maior, o valor pago será integralmente restituído." },
    { titulo: "5. Direito de arrependimento (CDC art. 49)", corpo: "Em contratações à distância, o CDC assegura o direito de arrependimento em 7 (sete) dias corridos após o aceite. O ressarcimento nesse prazo é integral, sem qualquer retenção, desde que o pedido de arrependimento seja formalizado por escrito ao ESPAÇO PERSONARE (via WhatsApp da(o) atendente responsável ou e-mail)." },
    { titulo: "6. Tratamento de dados pessoais (LGPD — Lei 13.709/18)", corpo: "Ao aceitar, o(a) CLIENTE(S) declara ciência de que o ESPAÇO PERSONARE tratará os dados pessoais fornecidos (nome completo, CPF, telefone, e-mail e dados do evento) com a base legal da execução de contrato (art. 7º, V, LGPD). Os dados serão usados exclusivamente para viabilizar o evento contratado, emitir contrato e nota fiscal, e cumprir obrigações legais e fiscais. A retenção mínima é a exigida pela legislação fiscal (5 anos após o encerramento). Solicitações de acesso, correção ou exclusão podem ser feitas por escrito ao atendente responsável." },
    { titulo: "7. Assinatura eletrônica e prova (Lei 14.063/2020 e MP 2.200-2/2001)", corpo: `O aceite se dá por assinatura eletrônica simples, admitida entre as partes com base no art. 219 do Código Civil e nos arts. 4º e 5º da Lei 14.063/2020. Para fins de prova, este aceite registra, junto com o registro na base de dados do ESPAÇO PERSONARE: nome completo, CPF, endereço IP de origem, User-Agent do navegador, data e hora precisas do clique, e a versão dos termos vigente no ato (v${TERMOS_VERSAO}). Estes dados são conservados na forma do Marco Civil da Internet (Lei 12.965/14) e permanecem armazenados pelo prazo mínimo de 5 (cinco) anos.` },
    { titulo: "8. Contrato definitivo", corpo: "Este aceite eletrônico não substitui o contrato definitivo de prestação de serviços, que será enviado em seguida contendo todas as cláusulas específicas (multas exatas, condições de pagamento detalhadas, política de cancelamento por escalonamento de prazo, obrigações operacionais de dia de evento). O(a) CLIENTE(S) declara ciência de que a assinatura do contrato definitivo é etapa obrigatória para a realização do evento." },
    { titulo: "9. Foro", corpo: "Fica eleito o foro da Comarca de Ponta Grossa/PR para dirimir eventuais questões oriundas deste acordo, salvo se disposição legal em contrário (por exemplo, foro do domicílio do consumidor, conforme CDC)." },
  ];
}
